### PR TITLE
fix: enforced MainActor on DemoModel state & removed NavigationStack

### LINKED ISSUE #620: Demo App State Transitions are Unreliable
I apologize in advance for the extremely vague bug report, but I've observed the following with recent versions of the demo app after some architectural changes:

* The state cycle button does not have any obvious effect sometimes.
* Occasionally, console messages indicate that something went wrong; other times not. For example, one common one I encounter is `void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL`. 
* Thread safety issues:

```
Main Thread Checker: UI API called on a background thread: -[UIImageView setHidden:]
PID: 10266, TID: 101512, Thread name: (none), Queue name: com.apple.root.user-initiated-qos.cooperative, QoS: 25
Backtrace:
4   Ferrostar Demo.debug.dylib          0x0000000101aa7590 $s15MapLibreSwiftUI0A4ViewV14applyModifiers33_33F8D08E927C18206E51A68216F33BDALL_9runUnsafeyx_SbtF + 524
5   Ferrostar Demo.debug.dylib          0x0000000101aa7b30 $s15MapLibreSwiftUI0A4ViewV22updateUIViewController_7contextyx_0cD00gH20RepresentableContextVyACyxGGtF + 404
6   Ferrostar Demo.debug.dylib          0x0000000101aa7e94 $s15MapLibreSwiftUI0A4ViewVyxG0cD029UIViewControllerRepresentableAaeFP06updatefG0_7contexty0fG4TypeQz_AE0fgH7ContextVyxGtFTW + 12
7   SwiftUI                             0x00000001d340356c $s7SwiftUI42PlatformViewControllerRepresentableAdaptorV06updateD8Provider_7contexty06UIViewE4TypeQz_AA0cdF7ContextVyACyxGGtF + 236
8   SwiftUI                             0x00000001d39bddec $s7SwiftUI17PlatformViewChildV11updateValueyyFyyXEfU_yyXEfU3_yyXEfU_yyXEfU_yyXEfU_ + 112
9   SwiftUI                             0x00000001d39bdd04 $s7SwiftUI17PlatformViewChildV11updateValueyyFyyXEfU_yyXEfU3_yyXEfU_yyXEfU_ + 344
10  SwiftUICore                         0x00000001d46e4d04 $s7SwiftUI16ViewRendererHostPAAE21performExternalUpdateyyyyXEF + 260
11  SwiftUI                             0x00000001d39c25c4 $s7SwiftUI17PlatformViewChildV11updateValueyyFyyXEfU_yyXEfU3_yyXEfU_7performL_4workyyyXE_tAA0cD13RepresentableRzlFyyXEfU_TA + 64
12  SwiftUICore                         0x00000001d422a554 $s7SwiftUI6UpdateO6ensureyxxyKXEKlFZxyKXEfU_ + 48
13  SwiftUICore                         0x00000001d42295f0 $s7SwiftUI6UpdateO6ensureyxxyKXEKlFZ + 96
14  SwiftUI                             0x00000001d39bdb00 $s7SwiftUI17PlatformViewChildV11updateValueyyFyyXEfU_yyXEfU3_yyXEfU_ + 444
15  SwiftUI                             0x00000001d39c254c $s7SwiftUI17PlatformViewChildV11updateValueyyFyyXEfU_yyXEfU3_TA + 96
16  SwiftUICore                         0x00000001d43ecfa0 $s7SwiftUI16_withObservation2dox5value_0D00D8TrackingV11_AccessListVSg06accessI0txyKXE_tKlFxSpyAJGKXEfU_ + 84
17  SwiftUICore                         0x00000001d4080a18 $s7SwiftUI16_withObservation2dox5value_0D00D8TrackingV11_AccessListVSg06accessI0txyKXE_tKlFxSpyAJGKXEfU_TA + 24
18  SwiftUICore                         0x00000001d4225198 $ss17withUnsafePointer2to_q0_x_q0_SPyxGq_YKXEtq_YKs5ErrorR_Ri_zRi_0_r1_lF + 72
19  SwiftUICore                         0x00000001d43ec684 $s14AttributeGraph12StatefulRuleP7SwiftUIE15withObservation2doqd__qd__yKXE_tKlFTm + 544
20  SwiftUICore                         0x00000001d43ec3dc $s14AttributeGraph12StatefulRuleP7SwiftUIE15withObservation2doqd__qd__yKXE_tKlF + 56
21  SwiftUI                             0x00000001d39bcba8 $s7SwiftUI17PlatformViewChildV11updateValueyyFyyXEfU_ + 3044
22  SwiftUICore                         0x00000001d406ee14 $s7SwiftUI8SignpostV13traceInterval6object__7closurexyXlSg_s12StaticStringVSays7CVarArg_pGyXKxyXEtlF + 344
23  SwiftUI                             0x00000001d39bbe80 $s7SwiftUI17PlatformViewChildV11updateValueyyF + 164
24  SwiftUI                             0x00000001d2c9360c $s14AttributeGraph0A0VyACyxGqd__c5ValueQyd__RszAA12StatefulRuleRd__lufcADSPyqd__GXEfU_ySv_So11AGAttributeatcyXEfU_ySv_AJtcfu_TA + 28
25  AttributeGraph                      0x00000001beeaef54 _ZN2AG5Graph11UpdateStack6updateEv + 532
26  AttributeGraph                      0x00000001beeaf7a4 _ZN2AG5Graph16update_attributeENS_4data3ptrINS_4NodeEEEj + 432
27  AttributeGraph                      0x00000001beebd040 _ZN2AG8Subgraph6updateEj + 828
28  SwiftUICore                         0x00000001d43d40c8 $s7SwiftUI9GraphHostC17flushTransactionsyyF + 840
29  SwiftUICore                         0x00000001d3f0ae74 $s7SwiftUI9GraphHostC16asyncTransaction_2id8mutation5style14mayDeferUpdateyAA0F0V_AJ2IDVxAA01_C14Mutation_StyleOSbtAA0cN0RzlFAA011ObservationcN033_7DF024579E4FC31D4E92A33BBA0366D6LLV_TB5 + 576
30  SwiftUICore                         0x00000001d43edb10 $s7Swi
```

* The X button not responding to input
* Inability to run another route after exiting nav via the X button

I'm not sure what the root cause is (and recent iOS simulator bugs, like networking randomly saying it's dropped, requiring a host system restart and not just a mere simulator reboot make it worse!). But it feels like the recent state modeling changes are _probably_ a least partly to blame. Perhaps actors might help here to solve the race issues?

cc @bolsinga @Archdoog

### PR DESCRIPTION
**Pull request by Archdoog**
- Revised DemoModel to improve unexpected swift concurrency behaviors.
- Removes unused NavigationStack.

This may fix #620 

The main actor stuff is likely overkill - but it'll help assure that UI only get's manipulated on the MainActor.

### CODE REVIEW

File: apple/DemoApp/Demo/DemoNavigationView.swift [hunk 1]
```diff
@@ -50,108 +50,110 @@ struct DemoNavigationView: View {
     var body: some View {
         let locationServicesEnabled = model.locationServicesEnabled
 
-        NavigationStack {
```
Comment (Archdoog) [inline apple/DemoApp/Demo/DemoNavigationView.swift:53]: Remove this seems to have massively improved things even on main. Seems like there's some SwiftUI behavior that's blocking the touch points on the buttons 😅

**Comment by ianthetechie** [comment]
In also "could be related", I'm still testing on Xcode 16, but I have the beta SDKs and Xcode around which sometimes interfere with things...

Maybe Containers was really just a hint that next year, for the first time in 25 years, you'll actually be able to have a proper test environment for your Apple projects*

* - Well, as long as you don't use Xcode. I mean, seriously, who uses Xcode? Obviously nobody at Apple 🧌

File: apple/DemoApp/Demo/DemoNavigationView.swift (hunk 1 above)
Comment (bolsinga) [reply apple/DemoApp/Demo/DemoNavigationView.swift:53]: Is it possible to make a separate patch for this change? I'd always wondered why this was there w/o a navigation path.

Comment (Archdoog) [reply apple/DemoApp/Demo/DemoNavigationView.swift:53]: It was originally to host a settings scene. So totally fine to drop it 👍

File: apple/DemoApp/Demo/DemoModel.swift [hunk 2]
```diff
@@ -133,29 +133,26 @@ let demoModel = DemoModel()
...
+            }
         }
     }
 
-    func chooseDestination() {
-        wrap {
-            try appState.setDestination(destination)
+    func chooseDestination() async {
+        await wrap {
+            try await appState.setDestination(destination)
```
Comment (ianthetechie) [inline apple/DemoApp/Demo/DemoModel.swift:155]: This doesn't actually do anything async, so that triggers a compiler warning FWIW.
